#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: give your study group a name and a short description:
title: OHSU Data Science Institute
description: "The OHSU Data Science Institute will bring together researchers, librarians, and information specialists for formal training on key topics in data science. The program will be offered as a three-day workshop from November 6-8, 2017 at the White Stag Building in Portland, Oregon."

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

headlineSmall: "Welcome to the OHSU Library Data Science Institute!"
headlineMain: "November 6-8, 2017"
avatar: "img/logos/LogoTree_v2.png"


# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public'
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: True
calendar_embed_url: "https://calendar.google.com/calendar/embed?src=t8v2ij727ctg6upd3v8ampd8q4%40group.calendar.google.com&ctz=America/Los_Angeles"
calendar_ical_url: "https://calendar.google.com/calendar/ical/t8v2ij727ctg6upd3v8ampd8q4%40group.calendar.google.com/public/basic.ics"

# ===============================
# Categories for sorting lessons.
# ===============================

languages:
  - python
  - r
  - git
  - misc

levels:
  - beginner
  - intermediate
  - advanced

#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
future: true
